services:
  mysql:
    image: mysql:8.0
    container_name: onboarding-wfms-db-service
    environment:
      MYSQL_ROOT_PASSWORD: pword123
      MYSQL_DATABASE: onboarding-wfms-db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql_data: