<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OnboardingWFMSApi.DataAccess\OnboardingWFMSApi.DataAccess.csproj" />
    <ProjectReference Include="..\OnboardingWFMSApi.DataModels\OnboardingWFMSApi.DataModels.csproj" />
  </ItemGroup>

</Project>
